Copyright = "All rights reserved - 2015"
DisqusShortname = "yo_0"
LanguageCode = "fr-FR"
Title = "Awesome content for web dev"
baseurl = "https://mymk.github.io"
canonifyurls = true
paginate = 5
theme = "casper"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[params]
RSSLink = "http://feeds.feedburner.com/"
author = "Yoan Marchal"
authorlocation = "Limoges, France"
authorwebsite = "http://yoanmarchal.com"
bio = "French freelance"
cover = "images/cover_brain.jpg"
description = "this is my description"
githubName = "mymk"
googleAnalyticsUserID = ""
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "mymk"
